@startuml Smart_Energy_Manager

skinparam classAttributeIconSize 0
skinparam classFontSize 13
skinparam classHeaderBackgroundColor #dae8fc
skinparam classBorderColor #6c8ebf
skinparam ArrowColor #333333
skinparam linetype ortho

' ══════════════════════
' MODEL
' ══════════════════════

class Coordonnees {
  - x : int
  - y : int
  --
  + getX() : int
  + getY() : int
}

abstract class Batiment {
  - id : int
  - nom : String
  - surface : int
  - coordonnees : Coordonnees
  - releves : List<Releve>
  --
  + getId() : int
  + getNom() : String
  + getSurface() : int
  + getCoordonnees() : Coordonnees
  + getListeReleves() : List<Releve>
  + ajouterReleve(r : Releve) : void
  # calculerReleve(date : LocalDate, type : TypeEnergie, coefMin : double, coefMax : double) : Releve
  + genererReleves(date : LocalDate) : void
  # {abstract} genererElectricite(date : LocalDate) : Releve
  # {abstract} genererEau(date : LocalDate) : Releve
  # {abstract} genererGaz(date : LocalDate) : Releve
  # {abstract} genererChauffage(date : LocalDate) : Releve
  # {abstract} genererClimatisation(date : LocalDate) : Releve
}

Batiment *-- Coordonnees : possède

class Maison {
}

class Appartement {
}

class Bureau {
}

class LocalCommercial {
}

class BatimentUniversitaire {
}

class Releve {
  - date : LocalDate
  - typeEnergie : TypeEnergie
  - quantite : double
  - cout : double
  --
  + getDate() : LocalDate
  + getTypeEnergie() : TypeEnergie
  + getQuantite() : double
  + getCout() : double
}

enum TypeEnergie {
  ELECTRICITE
  EAU
  GAZ
  CHAUFFAGE
  CLIMATISATION
  --
  - unite : String
  - prixUnitaire : double
  + getUnite() : String
  + getPrixUnitaire() : double

}

' ══════════════════════
' SERVICES
' ══════════════════════

class BatimentService {
  - batiments : List<Batiment>
  --
  + ajouterBatiment(b : Batiment) : void
  + supprimerBatiment(b : Batiment) : void
  + modifierBatiment(b : Batiment) : void
  + getTousBatiments() : List<Batiment>
  + genererReleveUnJour(date : LocalDate) : void
  + sauvegarder() : void
  + charger() : List<Batiment>
}

class StatistiquesService {
  - batimentService : BatimentService
  --
  + consommationTotaleJour(date : LocalDate) : double
  + consommationTotaleMois(mois : int, annee : int) : double
  + coutTotalMois(mois : int, annee : int) : double
  + batimentPlusConsommateur() : Batiment
  + energieDominante() : TypeEnergie
  + detecterAnomalie(b : Batiment) : boolean
}

class Simulation {
  - dateSimulation : LocalDate
  - batimentService : BatimentService
  --
  + getDateSimulation() : LocalDate
  + avancerJour() : void
  + avancerUnMois() : void
}

class JsonPersistanceService {
  - cheminFichier : String
  --
  + sauvegarder(batiments : List<Batiment>) : void
  + charger() : List<Batiment>
}

class CalendrierService {
  --
  + {static} estWeekend(date : LocalDate) : boolean
  + {static} estVacancesScolaires(date : LocalDate) : boolean
  + {static} getSaison(date : LocalDate) : Saison
}

enum Saison {
  HIVER
  PRINTEMPS
  ETE
  AUTOMNE
}



' ══════════════════════
' RELATIONS
' ══════════════════════

Batiment <|-- Maison
Batiment <|-- Appartement
Batiment <|-- Bureau
Batiment <|-- LocalCommercial
Batiment <|-- BatimentUniversitaire

Batiment "1" *-- "0..*" Releve : contient

Releve --> TypeEnergie : utilise

BatimentService "1" o-- "0..*" Batiment : gère
BatimentService ..> JsonPersistanceService : utilise

StatistiquesService ..> BatimentService : dépend de
Simulation ..> BatimentService : dépend de

CalendrierService ..> Saison : utilise
Batiment ..> CalendrierService : utilise


@enduml
